name: Slapper
author: jojoe77777
version: 1.6.2
description: Slapper, the NPC plugin for PocketMine-MP
main: slapper\Main
api: 3.13.0
mcpe-protocol: [361, 388, 389, 390, 407, 408, 419]
website: https://github.com/jojoe77777/Slapper

commands:
  slapper:
    description: Create a Slapper NPC, or edit an existing one!
    usage: "/slapper [args]..."
    permission: slapper.command
  rca:
    description: Execute a command as someone else!
    usage: "/rca <player> <command>"
    permission: slapper.rca
  nothing:
    description: Do nothing!
    usage: "/nothing"
    permission: slapper.nothing

permissions:
  slapper:
    description: Allow using all Slapper commands
    default: op
    children:
      slapper.command:
        description: Allow using /slapper
        default: op
      slapper.create:
        description: Allow using command /slapper create
        default: op
      slapper.edit:
        description: Allow editing Slapper entity data with /slapper edit
        default: op
      slapper.nothing:
        description: Allow doing nothing
        default: op
      slapper.rca:
        description: Allow running commands as other players
        default: op
      slapper.remove:
        description: Allow removing Slapper entities with /slapper remove [id]
        default: op
      slapper.id:
        description: Allow viewing entity ID
        default: op
      slapper.help:
        description: Allow viewing Slapper help page
        default: op
